[package]
name = "fast3d"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
wgpu.workspace = true
bytemuck.workspace = true
log.workspace = true
egui = { version = "0.35", optional = true }
egui-wgpu = { version = "0.35", optional = true }

[dev-dependencies]
wgpu = { version = "29.0", features = ["wgsl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"

[features]
default = []
asm = []
debug-ui = ["dep:egui", "dep:egui-wgpu"]
