// @generated by `cargo run -p fast3d-fixtures -- registry`; do not edit.
use super::EmbeddedFixture;

pub(super) static EMBEDDED: &[EmbeddedFixture] = &[
    EmbeddedFixture {
        id: "literal/colored-triangle/v1",
        manifest: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/literal/colored-triangle/v1/fixture.toml"
        )),
        manifest_sha256: "100cfb17fccd99f4ba1afd88493b7347ed7cbf92901f5069d6b19c3683745930",
        rdram: include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/literal/colored-triangle/v1/image.rdram"
        )),
        dump: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/literal/colored-triangle/v1/image.dump"
        )),
    },
    EmbeddedFixture {
        id: "scene/morphcube/t-00000000/tex-white1",
        manifest: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-00000000/tex-white1/fixture.toml"
        )),
        manifest_sha256: "112fc0695d87d84d6e9c816639a2a53db67b49f07b604ed33d38c46ba5076ce0",
        rdram: include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-00000000/tex-white1/image.rdram"
        )),
        dump: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-00000000/tex-white1/image.dump"
        )),
    },
    EmbeddedFixture {
        id: "scene/morphcube/t-3fc90fdb/tex-white1",
        manifest: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-3fc90fdb/tex-white1/fixture.toml"
        )),
        manifest_sha256: "7ac34929589364014d45018813fb7789cb230851bd371714d1026e7f9a3dcdfe",
        rdram: include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-3fc90fdb/tex-white1/image.rdram"
        )),
        dump: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-3fc90fdb/tex-white1/image.dump"
        )),
    },
    EmbeddedFixture {
        id: "scene/morphcube/t-40490fdb/tex-white1",
        manifest: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-40490fdb/tex-white1/fixture.toml"
        )),
        manifest_sha256: "373cf77f1083f05eae9d7fab2105d4ac8da13a0fa244fca683d962f461d42818",
        rdram: include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-40490fdb/tex-white1/image.rdram"
        )),
        dump: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/v1/scene/morphcube/t-40490fdb/tex-white1/image.dump"
        )),
    },
];
