pub(crate) const SCENES: &[&str] = &[
    "alpha-threshold",
    "backface-culling",
    "chrome-icosphere",
    "ci4-canary",
    "ci4-grid",
    "ci8-canary",
    "ci8-ramp",
    "decal",
    "fill-texrect",
    "flat-color",
    "fogworld",
    "framebuffer-extent",
    "high-poly",
    "hud-over-3d",
    "i4-ramp",
    "i8-ramp",
    "ia16-ramp",
    "ia4-ramp",
    "ia8-ramp",
    "lights",
    "matrix-stack",
    "mirror-repeat",
    "morphcube",
    "multi-material",
    "offscreen-then-sample",
    "onetri",
    "perspective-cube",
    "segmented-sub-dl",
    "texrectflip",
    "textured-quad",
    "tron",
    "two-cycle-combiner",
    "wrap-repeat",
];

const FIXTURES: &[(&str, u64, &[u8])] = &[
    (
        "alpha-threshold",
        2256,
        include_bytes!("../../tests/fixtures/assembled/alpha-threshold.rdram"),
    ),
    (
        "alpha-threshold--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/alpha-threshold--white64.rdram"),
    ),
    (
        "backface-culling",
        2240,
        include_bytes!("../../tests/fixtures/assembled/backface-culling.rdram"),
    ),
    (
        "backface-culling--white64",
        8384,
        include_bytes!("../../tests/fixtures/assembled/backface-culling--white64.rdram"),
    ),
    (
        "chrome-icosphere",
        3800,
        include_bytes!("../../tests/fixtures/assembled/chrome-icosphere.rdram"),
    ),
    (
        "chrome-icosphere--white64",
        9944,
        include_bytes!("../../tests/fixtures/assembled/chrome-icosphere--white64.rdram"),
    ),
    (
        "ci4-canary",
        728,
        include_bytes!("../../tests/fixtures/assembled/ci4-canary.rdram"),
    ),
    (
        "ci4-canary--white64",
        2264,
        include_bytes!("../../tests/fixtures/assembled/ci4-canary--white64.rdram"),
    ),
    (
        "ci4-grid",
        728,
        include_bytes!("../../tests/fixtures/assembled/ci4-grid.rdram"),
    ),
    (
        "ci4-grid--white64",
        2264,
        include_bytes!("../../tests/fixtures/assembled/ci4-grid--white64.rdram"),
    ),
    (
        "ci8-canary",
        1240,
        include_bytes!("../../tests/fixtures/assembled/ci8-canary.rdram"),
    ),
    (
        "ci8-canary--white64",
        4312,
        include_bytes!("../../tests/fixtures/assembled/ci8-canary--white64.rdram"),
    ),
    (
        "ci8-ramp",
        1240,
        include_bytes!("../../tests/fixtures/assembled/ci8-ramp.rdram"),
    ),
    (
        "ci8-ramp--white64",
        4312,
        include_bytes!("../../tests/fixtures/assembled/ci8-ramp--white64.rdram"),
    ),
    (
        "decal",
        2384,
        include_bytes!("../../tests/fixtures/assembled/decal.rdram"),
    ),
    (
        "decal--white64",
        8528,
        include_bytes!("../../tests/fixtures/assembled/decal--white64.rdram"),
    ),
    (
        "fill-texrect",
        2064,
        include_bytes!("../../tests/fixtures/assembled/fill-texrect.rdram"),
    ),
    (
        "fill-texrect--white64",
        8208,
        include_bytes!("../../tests/fixtures/assembled/fill-texrect--white64.rdram"),
    ),
    (
        "flat-color",
        2256,
        include_bytes!("../../tests/fixtures/assembled/flat-color.rdram"),
    ),
    (
        "flat-color--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/flat-color--white64.rdram"),
    ),
    (
        "fogworld",
        2320,
        include_bytes!("../../tests/fixtures/assembled/fogworld.rdram"),
    ),
    (
        "fogworld--white64",
        8464,
        include_bytes!("../../tests/fixtures/assembled/fogworld--white64.rdram"),
    ),
    (
        "framebuffer-extent",
        2256,
        include_bytes!("../../tests/fixtures/assembled/framebuffer-extent.rdram"),
    ),
    (
        "framebuffer-extent--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/framebuffer-extent--white64.rdram"),
    ),
    (
        "high-poly",
        2688,
        include_bytes!("../../tests/fixtures/assembled/high-poly.rdram"),
    ),
    (
        "high-poly--white64",
        8832,
        include_bytes!("../../tests/fixtures/assembled/high-poly--white64.rdram"),
    ),
    (
        "hud-over-3d",
        2256,
        include_bytes!("../../tests/fixtures/assembled/hud-over-3d.rdram"),
    ),
    (
        "hud-over-3d--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/hud-over-3d--white64.rdram"),
    ),
    (
        "i4-ramp",
        720,
        include_bytes!("../../tests/fixtures/assembled/i4-ramp.rdram"),
    ),
    (
        "i4-ramp--white64",
        2256,
        include_bytes!("../../tests/fixtures/assembled/i4-ramp--white64.rdram"),
    ),
    (
        "i8-ramp",
        1232,
        include_bytes!("../../tests/fixtures/assembled/i8-ramp.rdram"),
    ),
    (
        "i8-ramp--white64",
        4304,
        include_bytes!("../../tests/fixtures/assembled/i8-ramp--white64.rdram"),
    ),
    (
        "ia16-ramp",
        2256,
        include_bytes!("../../tests/fixtures/assembled/ia16-ramp.rdram"),
    ),
    (
        "ia16-ramp--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/ia16-ramp--white64.rdram"),
    ),
    (
        "ia4-ramp",
        720,
        include_bytes!("../../tests/fixtures/assembled/ia4-ramp.rdram"),
    ),
    (
        "ia4-ramp--white64",
        2256,
        include_bytes!("../../tests/fixtures/assembled/ia4-ramp--white64.rdram"),
    ),
    (
        "ia8-ramp",
        1232,
        include_bytes!("../../tests/fixtures/assembled/ia8-ramp.rdram"),
    ),
    (
        "ia8-ramp--white64",
        4304,
        include_bytes!("../../tests/fixtures/assembled/ia8-ramp--white64.rdram"),
    ),
    (
        "lights",
        4296,
        include_bytes!("../../tests/fixtures/assembled/lights.rdram"),
    ),
    (
        "lights--white64",
        10440,
        include_bytes!("../../tests/fixtures/assembled/lights--white64.rdram"),
    ),
    (
        "matrix-stack",
        2432,
        include_bytes!("../../tests/fixtures/assembled/matrix-stack.rdram"),
    ),
    (
        "matrix-stack--white64",
        8576,
        include_bytes!("../../tests/fixtures/assembled/matrix-stack--white64.rdram"),
    ),
    (
        "mirror-repeat",
        2256,
        include_bytes!("../../tests/fixtures/assembled/mirror-repeat.rdram"),
    ),
    (
        "mirror-repeat--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/mirror-repeat--white64.rdram"),
    ),
    (
        "morphcube",
        2672,
        include_bytes!("../../tests/fixtures/assembled/morphcube.rdram"),
    ),
    (
        "morphcube--white64",
        8816,
        include_bytes!("../../tests/fixtures/assembled/morphcube--white64.rdram"),
    ),
    (
        "multi-material",
        2384,
        include_bytes!("../../tests/fixtures/assembled/multi-material.rdram"),
    ),
    (
        "multi-material--white64",
        8528,
        include_bytes!("../../tests/fixtures/assembled/multi-material--white64.rdram"),
    ),
    (
        "offscreen-then-sample",
        2064,
        include_bytes!("../../tests/fixtures/assembled/offscreen-then-sample.rdram"),
    ),
    (
        "offscreen-then-sample--white64",
        8208,
        include_bytes!("../../tests/fixtures/assembled/offscreen-then-sample--white64.rdram"),
    ),
    (
        "onetri",
        2256,
        include_bytes!("../../tests/fixtures/assembled/onetri.rdram"),
    ),
    (
        "onetri--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/onetri--white64.rdram"),
    ),
    (
        "perspective-cube",
        2384,
        include_bytes!("../../tests/fixtures/assembled/perspective-cube.rdram"),
    ),
    (
        "perspective-cube--white64",
        8528,
        include_bytes!("../../tests/fixtures/assembled/perspective-cube--white64.rdram"),
    ),
    (
        "segmented-sub-dl",
        2384,
        include_bytes!("../../tests/fixtures/assembled/segmented-sub-dl.rdram"),
    ),
    (
        "segmented-sub-dl--white64",
        8528,
        include_bytes!("../../tests/fixtures/assembled/segmented-sub-dl--white64.rdram"),
    ),
    (
        "texrectflip",
        2064,
        include_bytes!("../../tests/fixtures/assembled/texrectflip.rdram"),
    ),
    (
        "texrectflip--white64",
        8208,
        include_bytes!("../../tests/fixtures/assembled/texrectflip--white64.rdram"),
    ),
    (
        "textured-quad",
        2256,
        include_bytes!("../../tests/fixtures/assembled/textured-quad.rdram"),
    ),
    (
        "textured-quad--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/textured-quad--white64.rdram"),
    ),
    (
        "tron",
        2320,
        include_bytes!("../../tests/fixtures/assembled/tron.rdram"),
    ),
    (
        "tron--white64",
        8464,
        include_bytes!("../../tests/fixtures/assembled/tron--white64.rdram"),
    ),
    (
        "two-cycle-combiner",
        2256,
        include_bytes!("../../tests/fixtures/assembled/two-cycle-combiner.rdram"),
    ),
    (
        "two-cycle-combiner--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/two-cycle-combiner--white64.rdram"),
    ),
    (
        "wrap-repeat",
        2256,
        include_bytes!("../../tests/fixtures/assembled/wrap-repeat.rdram"),
    ),
    (
        "wrap-repeat--white64",
        8400,
        include_bytes!("../../tests/fixtures/assembled/wrap-repeat--white64.rdram"),
    ),
    (
        "flat-color--white1",
        216,
        include_bytes!("../../tests/fixtures/assembled/flat-color--white1.rdram"),
    ),
    (
        "perspective-cube--white1",
        344,
        include_bytes!("../../tests/fixtures/assembled/perspective-cube--white1.rdram"),
    ),
    (
        "two-cycle-combiner--white1",
        216,
        include_bytes!("../../tests/fixtures/assembled/two-cycle-combiner--white1.rdram"),
    ),
    (
        "framebuffer-extent--white1",
        216,
        include_bytes!("../../tests/fixtures/assembled/framebuffer-extent--white1.rdram"),
    ),
    (
        "offscreen-then-sample--white1",
        24,
        include_bytes!("../../tests/fixtures/assembled/offscreen-then-sample--white1.rdram"),
    ),
    (
        "chrome-icosphere--orange",
        3800,
        include_bytes!("../../tests/fixtures/assembled/chrome-icosphere--orange.rdram"),
    ),
    (
        "chrome-icosphere--blue",
        3800,
        include_bytes!("../../tests/fixtures/assembled/chrome-icosphere--blue.rdram"),
    ),
    (
        "morphcube--t00000000",
        632,
        include_bytes!("../../tests/fixtures/assembled/morphcube--t00000000.rdram"),
    ),
    (
        "morphcube--t3fc90fdb",
        632,
        include_bytes!("../../tests/fixtures/assembled/morphcube--t3fc90fdb.rdram"),
    ),
    (
        "morphcube--t40490fdb",
        632,
        include_bytes!("../../tests/fixtures/assembled/morphcube--t40490fdb.rdram"),
    ),
    (
        "perspective-cube--t00000000",
        344,
        include_bytes!("../../tests/fixtures/assembled/perspective-cube--t00000000.rdram"),
    ),
    (
        "perspective-cube--t40000000",
        344,
        include_bytes!("../../tests/fixtures/assembled/perspective-cube--t40000000.rdram"),
    ),
    (
        "textured-quad--orange-blue",
        2256,
        include_bytes!("../../tests/fixtures/assembled/textured-quad--orange-blue.rdram"),
    ),
    (
        "textured-quad--blend-color",
        2256,
        include_bytes!("../../tests/fixtures/assembled/textured-quad--blend-color.rdram"),
    ),
    (
        "colored-triangle--white1",
        200,
        include_bytes!("../../tests/fixtures/assembled/colored-triangle--white1.rdram"),
    ),
    (
        "lookat--positive-z",
        48,
        include_bytes!("../../tests/fixtures/assembled/lookat--positive-z.rdram"),
    ),
    (
        "texrect--invalid-combiner",
        24,
        include_bytes!("../../tests/fixtures/assembled/texrect--invalid-combiner.rdram"),
    ),
    (
        "flat-color--vertex-colors",
        216,
        include_bytes!("../../tests/fixtures/assembled/flat-color--vertex-colors.rdram"),
    ),
    (
        "texrect--combiner-roles",
        24,
        include_bytes!("../../tests/fixtures/assembled/texrect--combiner-roles.rdram"),
    ),
    (
        "colored-triangle--missing-render-mode",
        192,
        include_bytes!(
            "../../tests/fixtures/assembled/colored-triangle--missing-render-mode.rdram"
        ),
    ),
    (
        "ci8--three-color-tlut",
        32,
        include_bytes!("../../tests/fixtures/assembled/ci8--three-color-tlut.rdram"),
    ),
    (
        "textured-quad--rgba16-4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/textured-quad--rgba16-4x4.rdram"),
    ),
    (
        "i8-ramp--4x4",
        224,
        include_bytes!("../../tests/fixtures/assembled/i8-ramp--4x4.rdram"),
    ),
    (
        "i4-ramp--4x4",
        216,
        include_bytes!("../../tests/fixtures/assembled/i4-ramp--4x4.rdram"),
    ),
    (
        "ia16-ramp--4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/ia16-ramp--4x4.rdram"),
    ),
    (
        "ia8-ramp--4x4",
        224,
        include_bytes!("../../tests/fixtures/assembled/ia8-ramp--4x4.rdram"),
    ),
    (
        "ia4-ramp--4x4",
        216,
        include_bytes!("../../tests/fixtures/assembled/ia4-ramp--4x4.rdram"),
    ),
    (
        "wrap-repeat--4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/wrap-repeat--4x4.rdram"),
    ),
    (
        "mirror-repeat--4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/mirror-repeat--4x4.rdram"),
    ),
    (
        "ci8-ramp--palette",
        1296,
        include_bytes!("../../tests/fixtures/assembled/ci8-ramp--palette.rdram"),
    ),
    (
        "ci8-ramp--canary",
        1296,
        include_bytes!("../../tests/fixtures/assembled/ci8-ramp--canary.rdram"),
    ),
    (
        "ci4-grid--palette",
        752,
        include_bytes!("../../tests/fixtures/assembled/ci4-grid--palette.rdram"),
    ),
    (
        "ci4-grid--canary",
        752,
        include_bytes!("../../tests/fixtures/assembled/ci4-grid--canary.rdram"),
    ),
    (
        "flat-color--translucent",
        216,
        include_bytes!("../../tests/fixtures/assembled/flat-color--translucent.rdram"),
    ),
    (
        "multi-material--rgba16-4x4",
        368,
        include_bytes!("../../tests/fixtures/assembled/multi-material--rgba16-4x4.rdram"),
    ),
    (
        "tron--empty-texture",
        272,
        include_bytes!("../../tests/fixtures/assembled/tron--empty-texture.rdram"),
    ),
    (
        "fogworld--empty-texture",
        272,
        include_bytes!("../../tests/fixtures/assembled/fogworld--empty-texture.rdram"),
    ),
    (
        "alpha-threshold--rgba16-4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/alpha-threshold--rgba16-4x4.rdram"),
    ),
    (
        "decal--empty-texture",
        336,
        include_bytes!("../../tests/fixtures/assembled/decal--empty-texture.rdram"),
    ),
    (
        "decal--in-front",
        272,
        include_bytes!("../../tests/fixtures/assembled/decal--in-front.rdram"),
    ),
    (
        "decal--behind",
        272,
        include_bytes!("../../tests/fixtures/assembled/decal--behind.rdram"),
    ),
    (
        "high-poly--empty-texture",
        640,
        include_bytes!("../../tests/fixtures/assembled/high-poly--empty-texture.rdram"),
    ),
    (
        "fill-texrect--rgba16-4x4",
        48,
        include_bytes!("../../tests/fixtures/assembled/fill-texrect--rgba16-4x4.rdram"),
    ),
    (
        "hud-over-3d--rgba16-4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/hud-over-3d--rgba16-4x4.rdram"),
    ),
    (
        "texrectflip--rgba16-4x4",
        48,
        include_bytes!("../../tests/fixtures/assembled/texrectflip--rgba16-4x4.rdram"),
    ),
    (
        "wrap-repeat--white4",
        240,
        include_bytes!("../../tests/fixtures/assembled/wrap-repeat--white4.rdram"),
    ),
    (
        "mirror-repeat--white4",
        240,
        include_bytes!("../../tests/fixtures/assembled/mirror-repeat--white4.rdram"),
    ),
    (
        "texrect--alpha-over-green",
        24,
        include_bytes!("../../tests/fixtures/assembled/texrect--alpha-over-green.rdram"),
    ),
    (
        "textured-quad--opaque-4x4",
        240,
        include_bytes!("../../tests/fixtures/assembled/textured-quad--opaque-4x4.rdram"),
    ),
];

pub(crate) fn fixture(name: &str) -> (&'static [u8], u64) {
    let &(_, entry, bytes) = FIXTURES
        .iter()
        .find(|&&(key, _, _)| key == name)
        .unwrap_or_else(|| panic!("unknown fixture: {name}"));
    (bytes, entry)
}
