name: validate
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:    
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      run: cargo clippy --all -- -D warnings
  macos-check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test
  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test
  windows-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test
